stages:
  - tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VERSION: "3.12"
  REDIS_PORT: 6378
  TEST_RQ_MAX_QUEUE_WAIT_TIME: 45
  FF_NETWORK_PER_BUILD: 1

tests:
  stage: tests
  image: python:${PYTHON_VERSION}
  script:
    # Install redis
    - apt-get update
    - apt-get install redis -y
    # Run the redis server
    - redis-server --daemonize yes --port "$REDIS_PORT"

    # Install project dependencies
    - pip install ."[dev]"

    # Check formatting
    - black --check app
    - isort --check-only app

    # Run unit tests
    - CPU_COUNT=$(python -c "import os; print(os.cpu_count())")
    - WORKER_COUNT=$(python -c "import os; print(min(os.cpu_count(), 4))")
    - echo "CPUs - $CPU_COUNT, WORKERS - $WORKER_COUNT"
    - echo "PYTEST_ARGS=$PYTEST_ARGS"
    - |
      if [ -z "$PYTEST_ARGS" ]; then 
        pytest -n "$WORKER_COUNT" --dist=loadscope app; 
      else 
        pytest $PYTEST_ARGS; 
      fi
  cache:
    paths:
      - .cache/pip
